version: "3"
services:
  landing-zone:
    image: hypernetlabs/landing-zone-daemon
    container_name: landing-zone-daemon
    command: --username 'tester1@gmail.com' --password 'tester1TESTER1' --backend 'https://profound-ripsaw-232522.appspot.com' --machine-id 'dan-1' --machine-name 'dan test'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
